### ISSUE TITLE
클러스터 생성 API 구현

### ISSUE THREAD

**Issue by HyeW** [doheez/K8s-Big-Data-Platform#52]
클라이언트에서 하둡/스파크 클러스터를 생성하기 위해 데이터를 전달하면
해당 데이터를 받아 쿠버네티스 엔진에게 전달해줍니다.

**Comment by HyeW** [comment]
클러스터관련 정보는 엔진쪽에서만 DB에 쓰고 꺼낼 수 있는게 맞나?
그렇다면
전달 데이터 형식은 어떻게 하는게 좋을까?
프론트 - 백은 아래처럼 dto를 정했는데 백-k8s엔진은 어떻게 해야하지?
```yml
{
 type: "spark"
 name: "my-cluster"
 count: "5"
}
```

@idoburnish @heohyeonjin
